In [ ]:
import csv

def load_csv_data(file_name="expense_data_1.csv"):
    data = []
    with open(file_name, mode='r') as file:
        csv_reader = csv.DictReader(file)
        for row in csv_reader:
            row['Amount'] = float(row['Amount'])  # Amount ko float mein kr rahe
            row['INR'] = float(row['INR'])        # INR ko float mein kar rahe
            data.append(row)
    print(f"Data loaded from {file_name}.")
    return data

def print_first_5_rows(data):
    print("\nFirst 5 rows of the dataset:")
    for i in range(min(5, len(data))):
        print(data[i])

def create_and_print_tuples(data):
    dates_tuple = tuple(entry["Date"] for entry in data)
    categories_tuple = tuple(entry["Category"] for entry in data)
    print("Tuple of Dates:", dates_tuple)
    print("Tuple of Categories:", categories_tuple)

def find_max_min_amount(data):
    amounts_tuple = tuple(entry["Amount"] for entry in data)
    max_amount = max(amounts_tuple)
    min_amount = min(amounts_tuple)
    print("Maximum Amount in the Tuple:", max_amount)
    print("Minimum Amount in the Tuple:", min_amount)

def count_transactions_by_category(data):
    category_counts = {}
    for entry in data:
        category = entry["Category"]
        if category in category_counts:
            category_counts[category] += 1
        else:
            category_counts[category] = 1
    print("Number of Transactions in Each Category:")
    for category, count in category_counts.items():
        print(f"{category}: {count}")

def print_unique_categories(data):
    unique_categories = set(entry["Category"] for entry in data)
    print("Unique Categories:", unique_categories)

def print_unique_dates(data):
    unique_dates = set(entry["Date"].split()[0] for entry in data)
    print("Unique Dates:", unique_dates)

def print_total_amount_by_category(data, category):
    total_amount = sum(entry["Amount"] for entry in data if entry["Category"] == category)
    print(f"Total amount for category '{category}': {total_amount}")

def print_transactions_above_amount(data, amount):
    transactions = [entry for entry in data if entry["Amount"] > amount]
    if transactions:
        print(f"Transactions above {amount}:")
        for transaction in transactions:
            print(transaction)
    else:
        print(f"No transactions found above {amount}.")

def calculate_total_amount(data):
    total_amount = sum(entry["Amount"] for entry in data)
    print(f"Total Amount of All Transactions: {total_amount}")

def calculate_average_amount(data):
    total_amount = sum(entry["Amount"] for entry in data)
    average_amount = total_amount / len(data)
    print(f"Average Amount of All Transactions: {average_amount}")

def main():
    data = load_csv_data()
    
    while True:
        print("Choose options ->")
        print("1 Print first 5 rows of the dataset")
        print("2 Create and print tuples of dates and categories")
        print("3 Finding maximum and minimum amounts")
        print("4 Count transactions by category")
        print("5 Print unique categories")
        print("6 Print unique dates")
        print("7 Total amount for a specific category")
        print("8 Transactions above a certain amount")
        print("9 Total amount of all transactions")
        print("10 Average amount of all transactions")
        print("11 Exit")
        
        choice = input("Enter your choice (1-11): ")
        
        if choice == '1':
            print_first_5_rows(data)
        elif choice == '2':
            create_and_print_tuples(data)
        elif choice == '3':
            find_max_min_amount(data)
        elif choice == '4':
            count_transactions_by_category(data)
        elif choice == '5':
            print_unique_categories(data)
        elif choice == '6':
            print_unique_dates(data)
        elif choice == '7':
            category = input("Enter the category: ")
            print_total_amount_by_category(data, category)
        elif choice == '8':
            amount = float(input("Enter the amount: "))
            print_transactions_above_amount(data, amount)
        elif choice == '9':
            calculate_total_amount(data)
        elif choice == '10':
            calculate_average_amount(data)
        elif choice == '11':
            print("Exiting the program.")
            break
        else:
            print("Invalid choice")

if __name__ == "__main__":
    main()

Data loaded from expense_data_1.csv.
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit

Enter your choice (1-11):  4

Number of Transactions in Each Category:
Food: 156
Other: 60
Transportation: 31
Social Life: 5
Household: 6
Apparel: 7
Education: 1
Salary: 1
Allowance: 6
Self-development: 1
Beauty: 1
Gift: 1
Petty cash: 1
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit

Enter your choice (1-11):  5

Unique Categories: {'Beauty', 'Household', 'Transportation', 'Salary', 'Petty cash', 'Self-development', 'Allowance', 'Other', 'Social Life', 'Food', 'Gift', 'Education', 'Apparel'}
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit

Enter your choice (1-11):  6

Unique Dates: {'1/28/2022', '12/20/2021', '2/4/2022', '12/11/2021', '2/18/2022', '11/25/2021', '1/21/2022', '11/23/2021', '2/25/2022', '1/14/2022', '12/14/2021', '12/27/2021', '2/17/2022', '11/27/2021', '2/3/2022', '12/9/2021', '11/30/2021', '2/21/2022', '2/20/2022', '12/3/2021', '2/11/2022', '1/30/2022', '1/7/2022', '12/5/2021', '1/15/2022', '3/2/2022', '12/12/2021', '12/23/2021', '12/21/2021', '2/28/2022', '1/29/2022', '1/10/2022', '2/23/2022', '1/13/2022', '12/19/2021', '1/27/2022', '2/27/2022', '1/6/2022', '2/7/2022', '11/29/2021', '1/23/2022', '1/17/2022', '1/11/2022', '12/8/2021', '2/12/2022', '12/17/2021', '1/31/2022', '12/28/2021', '2/26/2022', '2/2/2022', '12/2/2021', '12/6/2021', '1/25/2022', '2/8/2022', '11/24/2021', '2/6/2022', '1/19/2022', '2/16/2022', '2/10/2022', '12/16/2021', '12/18/2021', '2/13/2022', '3/1/2022', '2/24/2022', '1/8/2022', '1/2/2022', '1/26/2022', '1/4/2022', '12/1/2021', '12/30/2021', '1/12/2022', '11/22/2021', '1/18/2022', '1/24/2022', '2/22/2022', '12/7/2021', '11/28/2021', '11/21/2021', '12/4/2021', '1/1/2022', '2/19/2022', '1/5/2022', '12/25/2021', '11/26/2021', '12/10/2021', '1/3/2022', '12/24/2021'}
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit

Enter your choice (1-11):  7
Enter the category:  Food

Total amount for category 'Food': 23396.760000000002
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit

Enter your choice (1-11):  8
Enter the amount:  300

Transactions above 300.0:
{'Date': '3/1/2022 18:21', 'Account': '500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 500.0, 'Income/Expense': 'Income', 'Amount': 500.0, 'Currency': 'INR'}
{'Date': '2/28/2022 11:56', 'Account': '339.15', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 339.15, 'Income/Expense': 'Expense', 'Amount': 339.15, 'Currency': 'INR'}
{'Date': '2/26/2022 17:37', 'Account': '1500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 1500.0, 'Income/Expense': 'Income', 'Amount': 1500.0, 'Currency': 'INR'}
{'Date': '2/26/2022 16:01', 'Account': '1700', 'Category': 'Social Life', 'Subcategory': '', 'Note': '', 'INR': 1700.0, 'Income/Expense': 'Expense', 'Amount': 1700.0, 'Currency': 'INR'}
{'Date': '2/24/2022 22:32', 'Account': '303', 'Category': 'Household', 'Subcategory': '', 'Note': '', 'INR': 303.0, 'Income/Expense': 'Expense', 'Amount': 303.0, 'Currency': 'INR'}
{'Date': '2/24/2022 19:15', 'Account': '324.7', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 324.7, 'Income/Expense': 'Expense', 'Amount': 324.7, 'Currency': 'INR'}
{'Date': '2/23/2022 17:35', 'Account': '399', 'Category': 'Apparel', 'Subcategory': '', 'Note': '', 'INR': 399.0, 'Income/Expense': 'Expense', 'Amount': 399.0, 'Currency': 'INR'}
{'Date': '2/23/2022 12:38', 'Account': '399', 'Category': 'Apparel', 'Subcategory': '', 'Note': '', 'INR': 399.0, 'Income/Expense': 'Expense', 'Amount': 399.0, 'Currency': 'INR'}
{'Date': '2/21/2022 22:15', 'Account': '1300', 'Category': 'Transportation', 'Subcategory': '', 'Note': '', 'INR': 1300.0, 'Income/Expense': 'Expense', 'Amount': 1300.0, 'Currency': 'INR'}
{'Date': '2/21/2022 15:40', 'Account': '336', 'Category': 'Household', 'Subcategory': '', 'Note': '', 'INR': 336.0, 'Income/Expense': 'Expense', 'Amount': 336.0, 'Currency': 'INR'}
{'Date': '2/19/2022 21:35', 'Account': '1575', 'Category': 'Transportation', 'Subcategory': '', 'Note': '', 'INR': 1575.0, 'Income/Expense': 'Expense', 'Amount': 1575.0, 'Currency': 'INR'}
{'Date': '2/19/2022 20:45', 'Account': '380', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 380.0, 'Income/Expense': 'Expense', 'Amount': 380.0, 'Currency': 'INR'}
{'Date': '2/18/2022 23:01', 'Account': '348', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 348.0, 'Income/Expense': 'Expense', 'Amount': 348.0, 'Currency': 'INR'}
{'Date': '2/16/2022 16:57', 'Account': '475', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 475.0, 'Income/Expense': 'Expense', 'Amount': 475.0, 'Currency': 'INR'}
{'Date': '2/12/2022 21:20', 'Account': '491', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 491.0, 'Income/Expense': 'Expense', 'Amount': 491.0, 'Currency': 'INR'}
{'Date': '2/12/2022 14:47', 'Account': '10000', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 10000.0, 'Income/Expense': 'Income', 'Amount': 10000.0, 'Currency': 'INR'}
{'Date': '2/11/2022 22:41', 'Account': '373', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 373.0, 'Income/Expense': 'Expense', 'Amount': 373.0, 'Currency': 'INR'}
{'Date': '2/10/2022 20:15', 'Account': '641', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 641.0, 'Income/Expense': 'Expense', 'Amount': 641.0, 'Currency': 'INR'}
{'Date': '2/8/2022 10:37', 'Account': '1000', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Income', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '2/8/2022 9:18', 'Account': '2099', 'Category': 'Household', 'Subcategory': '', 'Note': '', 'INR': 2099.0, 'Income/Expense': 'Expense', 'Amount': 2099.0, 'Currency': 'INR'}
{'Date': '2/6/2022 17:52', 'Account': '1000', 'Category': 'Transportation', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Expense', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '2/6/2022 16:41', 'Account': '5000', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 5000.0, 'Income/Expense': 'Income', 'Amount': 5000.0, 'Currency': 'INR'}
{'Date': '2/6/2022 16:40', 'Account': '1500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 1500.0, 'Income/Expense': 'Expense', 'Amount': 1500.0, 'Currency': 'INR'}
{'Date': '2/2/2022 20:14', 'Account': '500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 500.0, 'Income/Expense': 'Income', 'Amount': 500.0, 'Currency': 'INR'}
{'Date': '1/27/2022 13:38', 'Account': '1500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 1500.0, 'Income/Expense': 'Income', 'Amount': 1500.0, 'Currency': 'INR'}
{'Date': '1/25/2022 9:20', 'Account': '325', 'Category': 'Transportation', 'Subcategory': '', 'Note': '', 'INR': 325.0, 'Income/Expense': 'Expense', 'Amount': 325.0, 'Currency': 'INR'}
{'Date': '1/23/2022 21:41', 'Account': '465', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 465.0, 'Income/Expense': 'Expense', 'Amount': 465.0, 'Currency': 'INR'}
{'Date': '1/23/2022 21:29', 'Account': '302', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 302.0, 'Income/Expense': 'Expense', 'Amount': 302.0, 'Currency': 'INR'}
{'Date': '1/23/2022 21:29', 'Account': '310', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 310.0, 'Income/Expense': 'Income', 'Amount': 310.0, 'Currency': 'INR'}
{'Date': '1/23/2022 21:27', 'Account': '2000', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 2000.0, 'Income/Expense': 'Income', 'Amount': 2000.0, 'Currency': 'INR'}
{'Date': '1/18/2022 20:54', 'Account': '301.15', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 301.15, 'Income/Expense': 'Expense', 'Amount': 301.15, 'Currency': 'INR'}
{'Date': '1/18/2022 12:59', 'Account': '1000', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Income', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '1/15/2022 21:17', 'Account': '1365', 'Category': 'Transportation', 'Subcategory': '', 'Note': '', 'INR': 1365.0, 'Income/Expense': 'Expense', 'Amount': 1365.0, 'Currency': 'INR'}
{'Date': '1/15/2022 21:16', 'Account': '1500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 1500.0, 'Income/Expense': 'Income', 'Amount': 1500.0, 'Currency': 'INR'}
{'Date': '1/14/2022 16:56', 'Account': '340', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 340.0, 'Income/Expense': 'Income', 'Amount': 340.0, 'Currency': 'INR'}
{'Date': '1/14/2022 16:54', 'Account': '340', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 340.0, 'Income/Expense': 'Income', 'Amount': 340.0, 'Currency': 'INR'}
{'Date': '1/14/2022 16:54', 'Account': '1530', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 1530.0, 'Income/Expense': 'Expense', 'Amount': 1530.0, 'Currency': 'INR'}
{'Date': '1/13/2022 19:10', 'Account': '1000', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Income', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '1/12/2022 22:44', 'Account': '479', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 479.0, 'Income/Expense': 'Expense', 'Amount': 479.0, 'Currency': 'INR'}
{'Date': '1/12/2022 13:25', 'Account': '301.75', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 301.75, 'Income/Expense': 'Expense', 'Amount': 301.75, 'Currency': 'INR'}
{'Date': '1/8/2022 13:45', 'Account': '535.3', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 535.3, 'Income/Expense': 'Expense', 'Amount': 535.3, 'Currency': 'INR'}
{'Date': '1/8/2022 13:38', 'Account': '4580', 'Category': 'Household', 'Subcategory': '', 'Note': '', 'INR': 4580.0, 'Income/Expense': 'Expense', 'Amount': 4580.0, 'Currency': 'INR'}
{'Date': '1/6/2022 21:30', 'Account': '440', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 440.0, 'Income/Expense': 'Income', 'Amount': 440.0, 'Currency': 'INR'}
{'Date': '1/6/2022 20:13', 'Account': '877.81', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 877.81, 'Income/Expense': 'Expense', 'Amount': 877.81, 'Currency': 'INR'}
{'Date': '1/5/2022 14:42', 'Account': '354', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 354.0, 'Income/Expense': 'Expense', 'Amount': 354.0, 'Currency': 'INR'}
{'Date': '1/5/2022 14:39', 'Account': '500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 500.0, 'Income/Expense': 'Expense', 'Amount': 500.0, 'Currency': 'INR'}
{'Date': '1/5/2022 14:37', 'Account': '500', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 500.0, 'Income/Expense': 'Expense', 'Amount': 500.0, 'Currency': 'INR'}
{'Date': '1/5/2022 14:30', 'Account': '388', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 388.0, 'Income/Expense': 'Expense', 'Amount': 388.0, 'Currency': 'INR'}
{'Date': '1/4/2022 22:11', 'Account': '1400', 'Category': 'Education', 'Subcategory': '', 'Note': '', 'INR': 1400.0, 'Income/Expense': 'Expense', 'Amount': 1400.0, 'Currency': 'INR'}
{'Date': '1/4/2022 22:10', 'Account': '8000', 'Category': 'Salary', 'Subcategory': '', 'Note': '', 'INR': 8000.0, 'Income/Expense': 'Income', 'Amount': 8000.0, 'Currency': 'INR'}
{'Date': '1/2/2022 14:16', 'Account': '725', 'Category': 'Transportation', 'Subcategory': '', 'Note': '', 'INR': 725.0, 'Income/Expense': 'Expense', 'Amount': 725.0, 'Currency': 'INR'}
{'Date': '1/1/2022 21:45', 'Account': '1000', 'Category': 'Allowance', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Income', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '12/25/2021 22:53', 'Account': '504', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 504.0, 'Income/Expense': 'Expense', 'Amount': 504.0, 'Currency': 'INR'}
{'Date': '12/25/2021 20:46', 'Account': '306', 'Category': 'Transportation', 'Subcategory': '', 'Note': '', 'INR': 306.0, 'Income/Expense': 'Expense', 'Amount': 306.0, 'Currency': 'INR'}
{'Date': '12/25/2021 19:50', 'Account': '400', 'Category': 'Self-development', 'Subcategory': '', 'Note': '', 'INR': 400.0, 'Income/Expense': 'Expense', 'Amount': 400.0, 'Currency': 'INR'}
{'Date': '12/18/2021 21:00', 'Account': '1000', 'Category': 'Allowance', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Income', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '12/18/2021 19:52', 'Account': '400', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 400.0, 'Income/Expense': 'Income', 'Amount': 400.0, 'Currency': 'INR'}
{'Date': '12/18/2021 19:51', 'Account': '363.72', 'Category': 'Social Life', 'Subcategory': '', 'Note': '', 'INR': 363.72, 'Income/Expense': 'Expense', 'Amount': 363.72, 'Currency': 'INR'}
{'Date': '12/11/2021 9:22', 'Account': '1000', 'Category': 'Allowance', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Income', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '12/6/2021 20:07', 'Account': '500', 'Category': 'Apparel', 'Subcategory': '', 'Note': '', 'INR': 500.0, 'Income/Expense': 'Expense', 'Amount': 500.0, 'Currency': 'INR'}
{'Date': '12/5/2021 18:41', 'Account': '1800', 'Category': 'Apparel', 'Subcategory': '', 'Note': '', 'INR': 1800.0, 'Income/Expense': 'Expense', 'Amount': 1800.0, 'Currency': 'INR'}
{'Date': '12/5/2021 12:23', 'Account': '4800', 'Category': 'Household', 'Subcategory': '', 'Note': '', 'INR': 4800.0, 'Income/Expense': 'Expense', 'Amount': 4800.0, 'Currency': 'INR'}
{'Date': '12/5/2021 12:23', 'Account': '8000', 'Category': 'Allowance', 'Subcategory': '', 'Note': '', 'INR': 8000.0, 'Income/Expense': 'Income', 'Amount': 8000.0, 'Currency': 'INR'}
{'Date': '12/4/2021 21:05', 'Account': '324', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 324.0, 'Income/Expense': 'Expense', 'Amount': 324.0, 'Currency': 'INR'}
{'Date': '12/3/2021 21:28', 'Account': '1000', 'Category': 'Allowance', 'Subcategory': '', 'Note': '', 'INR': 1000.0, 'Income/Expense': 'Income', 'Amount': 1000.0, 'Currency': 'INR'}
{'Date': '12/2/2021 20:07', 'Account': '504', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 504.0, 'Income/Expense': 'Expense', 'Amount': 504.0, 'Currency': 'INR'}
{'Date': '11/27/2021 13:46', 'Account': '2000', 'Category': 'Allowance', 'Subcategory': '', 'Note': '', 'INR': 2000.0, 'Income/Expense': 'Income', 'Amount': 2000.0, 'Currency': 'INR'}
{'Date': '11/21/2021 15:50', 'Account': '875', 'Category': 'Food', 'Subcategory': '', 'Note': '', 'INR': 875.0, 'Income/Expense': 'Expense', 'Amount': 875.0, 'Currency': 'INR'}
{'Date': '11/21/2021 13:30', 'Account': '2000', 'Category': 'Other', 'Subcategory': '', 'Note': '', 'INR': 2000.0, 'Income/Expense': 'Income', 'Amount': 2000.0, 'Currency': 'INR'}
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit

Enter your choice (1-11):  9

Total Amount of All Transactions: 112672.28
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit

Enter your choice (1-11):  10

Average Amount of All Transactions: 406.7591335740072
Choose options ->
1 Print first 5 rows of the dataset
2 Create and print tuples of dates and categories
3 Finding maximum and minimum amounts
4 Count transactions by category
5 Print unique categories
6 Print unique dates
7 Total amount for a specific category
8 Transactions above a certain amount
9 Total amount of all transactions
10 Average amount of all transactions
11 Exit